# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "clone_vm" {
  type = string
}

variable "proxmox_hostname" {
  type = string
}

variable "proxmox_node" {
  type = string
}

variable "proxmox_password" {
  type = string
}

variable "proxmox_username" {
  type = string
}

variable "ssh_password" {
  type = string
}

variable "ssh_username" {
  type = string
}

variable "version_tag" {
  type = string
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "proxmox-clone" "autogenerated_1" {
  clone_vm                 = "${var.clone_vm}"
  cores                    = 1
  full_clone               = false
  insecure_skip_tls_verify = true
  memory                   = 2048
  network_adapters {
    bridge = "vmbr0"
  }
  node                 = "${var.proxmox_node}"
  os                   = "l26"
  password             = "${var.proxmox_password}"
  proxmox_url          = "https://${var.proxmox_hostname}/api2/json"
  sockets              = 1
  ssh_password         = "${var.ssh_password}"
  ssh_timeout          = "90m"
  ssh_username         = "${var.ssh_username}"
  task_timeout         = "10m"
  template_description = "image made from packer"
  template_name        = "${var.clone_vm}${var.version_tag}"
  username             = "${var.proxmox_username}"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.proxmox-clone.autogenerated_1"]

  provisioner "shell" {
    inline       = ["echo ${var.version_tag} > provision.txt", "sudo apt update", "sudo apt -y upgrade", "sudo apt -y install apache2", "sudo apt -y install qemu-guest-agent cloud-init"]
    pause_before = "20s"
  }

}
